image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off  # использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-ibank.jar &

build_script:
  - profile=test
  - chmod +x gradlew
  - ./gradlew test --info  -Dselenide.headless=true
